name: Bump

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to deploy'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    name: "Bump project version"
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: git config user.name "bump-bot"
      - run: git config user.email "bump-bot@bump.bot"
      - run: npm version ${{ inputs.tag }}
      - run: git push origin ${{ github.ref_name }}

